# -*- coding: utf-8 -*-
"""DataAnalyticsProject2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mh456e0AtJaviAW0hroH5Tnq1HPRYl7R
"""

!pip install yfinance

import pandas as pd
import yfinance as yf

# Stocks for portfolio
stocks = ['AAPL','TSLA','MSFT','AMZN','GOOGL','NVDA','META','JPM']

# Download stock data
data = yf.download(stocks, start="2014-01-01", end="2024-01-01")

# Convert multi-index columns to rows
data = data.stack(level=1, future_stack=True).reset_index()

# Rename columns correctly
data.columns = ['Date','Stock','Open','High','Low','Close','Volume']

print("Dataset Shape:", data.shape)

data.head()

data.to_csv("raw_stock_dataset.csv", index=False)

from google.colab import files
files.download("raw_stock_dataset.csv")

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("raw_stock_dataset.csv")

df.head()

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

(df[['Open','High','Low','Close']] < 0).sum()

df.dtypes

df = df[df['Volume'] > 0]

df = df.dropna()

df.isnull().sum()

df['Date'] = pd.to_datetime(df['Date'])

df.dtypes

df = df.drop_duplicates()

df.duplicated().sum()

df = df.sort_values(by=['Stock','Date'])

df = df.reset_index(drop=True)

df.shape

df.to_csv("clean_stock_dataset.csv", index=False)

files.download("clean_stock_dataset.csv")

import pandas as pd

df = pd.read_csv("clean_stock_dataset.csv")

df.head()

df = df.sort_values(by=['Stock','Date'])
df = df.reset_index(drop=True)

df['Daily_Return'] = df.groupby('Stock')['Close'].pct_change()

df.head()

import numpy as np

df['Log_Return'] = np.log(df['Close'] / df.groupby('Stock')['Close'].shift(1))

df['MA_20'] = df.groupby('Stock')['Close'].transform(lambda x: x.rolling(window=20).mean())

df['MA_50'] = df.groupby('Stock')['Close'].transform(lambda x: x.rolling(window=50).mean())

df['Volatility_20'] = df.groupby('Stock')['Daily_Return'].transform(lambda x: x.rolling(window=20).std())

df.head()

df = df.dropna()

df.shape

df.to_csv("feature_engineered_stock_data.csv", index=False)

from google.colab import files
files.download("feature_engineered_stock_data.csv")